# TCL File Generated by Component Editor 21.1
# Fri Jun 21 11:19:42 CEST 2024
# DO NOT MODIFY


# 
# avalon_accel "Avalon DMA accelerator" v0.0
#  2024.06.21.11:19:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_accel
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_accel
set_module_property VERSION 0.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon DMA accelerator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_accel
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_accel.sv SYSTEM_VERILOG PATH ips/avalon_accel.sv TOP_LEVEL_FILE
add_fileset_file present_dp.sv SYSTEM_VERILOG PATH ips/present_dp.sv
add_fileset_file SBox.sv SYSTEM_VERILOG PATH ips/SBox.sv
add_fileset_file present.sv SYSTEM_VERILOG PATH ips/present.sv
add_fileset_file present_ctrl.sv SYSTEM_VERILOG PATH ips/present_ctrl.sv
add_fileset_file present_pkg.sv SYSTEM_VERILOG PATH ips/present_pkg.sv


# 
# parameters
# 
add_parameter s1 STD_LOGIC_VECTOR 0
set_parameter_property s1 DEFAULT_VALUE 0
set_parameter_property s1 DISPLAY_NAME s1
set_parameter_property s1 WIDTH 4
set_parameter_property s1 TYPE STD_LOGIC_VECTOR
set_parameter_property s1 UNITS None
set_parameter_property s1 ALLOWED_RANGES 0:15
set_parameter_property s1 HDL_PARAMETER true
add_parameter s2_1 STD_LOGIC_VECTOR 1
set_parameter_property s2_1 DEFAULT_VALUE 1
set_parameter_property s2_1 DISPLAY_NAME s2_1
set_parameter_property s2_1 WIDTH 4
set_parameter_property s2_1 TYPE STD_LOGIC_VECTOR
set_parameter_property s2_1 UNITS None
set_parameter_property s2_1 ALLOWED_RANGES 0:15
set_parameter_property s2_1 HDL_PARAMETER true
add_parameter s2_2 STD_LOGIC_VECTOR 2
set_parameter_property s2_2 DEFAULT_VALUE 2
set_parameter_property s2_2 DISPLAY_NAME s2_2
set_parameter_property s2_2 WIDTH 4
set_parameter_property s2_2 TYPE STD_LOGIC_VECTOR
set_parameter_property s2_2 UNITS None
set_parameter_property s2_2 ALLOWED_RANGES 0:15
set_parameter_property s2_2 HDL_PARAMETER true
add_parameter s3 STD_LOGIC_VECTOR 3
set_parameter_property s3 DEFAULT_VALUE 3
set_parameter_property s3 DISPLAY_NAME s3
set_parameter_property s3 WIDTH 4
set_parameter_property s3 TYPE STD_LOGIC_VECTOR
set_parameter_property s3 UNITS None
set_parameter_property s3 ALLOWED_RANGES 0:15
set_parameter_property s3 HDL_PARAMETER true
add_parameter s4_1 STD_LOGIC_VECTOR 4
set_parameter_property s4_1 DEFAULT_VALUE 4
set_parameter_property s4_1 DISPLAY_NAME s4_1
set_parameter_property s4_1 WIDTH 4
set_parameter_property s4_1 TYPE STD_LOGIC_VECTOR
set_parameter_property s4_1 UNITS None
set_parameter_property s4_1 ALLOWED_RANGES 0:15
set_parameter_property s4_1 HDL_PARAMETER true
add_parameter s4_2 STD_LOGIC_VECTOR 5
set_parameter_property s4_2 DEFAULT_VALUE 5
set_parameter_property s4_2 DISPLAY_NAME s4_2
set_parameter_property s4_2 WIDTH 4
set_parameter_property s4_2 TYPE STD_LOGIC_VECTOR
set_parameter_property s4_2 UNITS None
set_parameter_property s4_2 ALLOWED_RANGES 0:15
set_parameter_property s4_2 HDL_PARAMETER true
add_parameter s5 STD_LOGIC_VECTOR 6
set_parameter_property s5 DEFAULT_VALUE 6
set_parameter_property s5 DISPLAY_NAME s5
set_parameter_property s5 WIDTH 4
set_parameter_property s5 TYPE STD_LOGIC_VECTOR
set_parameter_property s5 UNITS None
set_parameter_property s5 ALLOWED_RANGES 0:15
set_parameter_property s5 HDL_PARAMETER true
add_parameter s6 STD_LOGIC_VECTOR 7
set_parameter_property s6 DEFAULT_VALUE 7
set_parameter_property s6 DISPLAY_NAME s6
set_parameter_property s6 WIDTH 4
set_parameter_property s6 TYPE STD_LOGIC_VECTOR
set_parameter_property s6 UNITS None
set_parameter_property s6 ALLOWED_RANGES 0:15
set_parameter_property s6 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
add_interface_port avalon_slave_0 avs_address address Input 5
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master_0
# 
add_interface avalon_master_0 avalon start
set_interface_property avalon_master_0 addressUnits SYMBOLS
set_interface_property avalon_master_0 associatedClock clock
set_interface_property avalon_master_0 associatedReset reset
set_interface_property avalon_master_0 bitsPerSymbol 8
set_interface_property avalon_master_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_0 burstcountUnits WORDS
set_interface_property avalon_master_0 doStreamReads false
set_interface_property avalon_master_0 doStreamWrites false
set_interface_property avalon_master_0 holdTime 0
set_interface_property avalon_master_0 linewrapBursts false
set_interface_property avalon_master_0 maximumPendingReadTransactions 0
set_interface_property avalon_master_0 maximumPendingWriteTransactions 0
set_interface_property avalon_master_0 readLatency 0
set_interface_property avalon_master_0 readWaitTime 1
set_interface_property avalon_master_0 setupTime 0
set_interface_property avalon_master_0 timingUnits Cycles
set_interface_property avalon_master_0 writeWaitTime 0
set_interface_property avalon_master_0 ENABLED true
set_interface_property avalon_master_0 EXPORT_OF ""
set_interface_property avalon_master_0 PORT_NAME_MAP ""
set_interface_property avalon_master_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_0 avm_write write Output 1
add_interface_port avalon_master_0 avm_read read Output 1
add_interface_port avalon_master_0 avm_waitrequest waitrequest Input 1
add_interface_port avalon_master_0 avm_writedata writedata Output 32
add_interface_port avalon_master_0 avm_readdata readdata Input 32
add_interface_port avalon_master_0 avm_address address Output 32


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender interrupt_sender_irq irq Output 1

